apiVersion: v1
kind: Service
metadata:
  name: auction-service
spec:
  type: NodePort
  selector:
    app: auction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010